name: travelsidecar

x-config:
  # Database configuration
  db-name: &db-name travelsidecar
  db-user: &db-user travelsidecaru
  db-password: &db-password travelsidecarpw
  db-port: &db-port 55432
  
  # MinIO configuration
  minio-user: &minio-user minio
  minio-password: &minio-password minio123
  minio-port: &minio-port 9090
  minio-console-port: &minio-console-port 9091
  minio-data-dir: &minio-data-dir /opt/travelsidecar/minio-data
  
  # Application configuration
  app-port: &app-port 8590
  app-https-port: &app-https-port 8591

services:
  travelsidecar-app:
    container_name: travelsidecar
    image: travelsidecar/travelsidecar:latest
    restart: unless-stopped
    ports:
      - "*app-port:8080"
      - "*app-https-port:8081"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: *db-name
      DB_USER: *db-user
      DB_PASSWORD: *db-password
      MINIO_ENDPOINT: minio:9000
      MINIO_ROOT_USER: *minio-user
      MINIO_ROOT_PASSWORD: *minio-password
      MINIO_USE_SSL: "false"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - travelsidecar-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  postgres:
    container_name: travelsidecar-database
    image: imresamu/postgis:17-3.5
    restart: unless-stopped
    ports:
      - "*db-port:5432"
    environment:
      POSTGRES_DB: *db-name
      POSTGRES_USER: *db-user
      POSTGRES_PASSWORD: *db-password
    volumes:
      - travelsidecar-postgres-data:/var/lib/postgresql/data
    networks:
      - travelsidecar-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  minio:
    container_name: travelsidecar-storage
    image: minio/minio:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:*minio-port:9000"
      - "127.0.0.1:*minio-console-port:9001"
    environment:
      MINIO_ROOT_USER: *minio-user
      MINIO_ROOT_PASSWORD: *minio-password
    volumes:
      - *minio-data-dir:/data
    command: server --console-address ":9001" /data
    networks:
      - travelsidecar-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

volumes:
  travelsidecar-postgres-data:
    name: travelsidecar-postgres-database

networks:
  travelsidecar-network:
    name: travelsidecar-network