name: Build and Publish Docker Image

on:
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set version variables
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          VERSION=${VERSION#v}
          if [[ $VERSION == .* ]]; then
            VERSION=${VERSION:1}
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Building version: $VERSION"

      - name: Update .NET project version
        run: |
          sed -i "s/<Version>.*<\/Version>/<Version>$VERSION<\/Version>/g" server/Api/Api.csproj
          cat server/Api/Api.csproj | grep Version

      - name: Update Angular version constant
        run: |
          echo "export const version = '${{ env.VERSION }}';" > web-client/src/app/version.ts
          cat web-client/src/app/version.ts

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push on Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/travelsidecar:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/travelsidecar:${{ env.VERSION }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/travelsidecar:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/travelsidecar:buildcache,mode=max